/**
 * Provides set data to the Cloud Function.
 * Reads from sets-data.json (generated by generate-sets-data.js predeploy script).
 */
"use strict";

const path = require("path");

let _cachedEras = null;

function getMinimalSets() {
  if (_cachedEras) return _cachedEras;
  _cachedEras = require(path.join(__dirname, "sets-data.json"));
  return _cachedEras;
}

module.exports = { getMinimalSets };
